version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      secrets:
        - sshkey
    volumes:
      - .:/app/repo
    environment:
      - DISPLAY=${DISPLAY}

secrets:
  sshkey:
    file: /Users/$USER/.ssh/id_ed25519
