behaviors:
  SharedPolicyBehavior:
    trainer_type: ppo
    hyperparameters:
      batch_size: 128
      buffer_size: 4000
      learning_rate: 3.0e-4
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
      memory: false
      goal_conditioning: false
    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.99
    max_steps: 10000000
    time_horizon: 1000
    summary_freq: 10000

environment_parameters:
  initialAgentCount:
    curriculum:
      - name: "default"
        completion_criteria: None
        value: 1

engine_settings:
  num_envs: 2
  max_steps: 0
  time_scale: 1.0
  capture_frame_rate: 60
  target_frame_rate: -1

checkpoint_settings:
  checkpoint_interval: 500000

