name: Build and Publish macOS Unity Project

#on:
#  push:
#    branches: [main]

on: workflow_dispatch

jobs:
  build-and-publish:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      
      - name: Build Unity Project for macOS
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneOSX
          buildName: libReplicantDriveSim
          buildsPath: Builds
          buildMethod: UnityDriveSimulation.BuildScript.PerformMacOSBuild
          customParameters: -development -debugCode

      - name: Package macOS Build
        run: |
          zip -r macos-unity-build.zip ./Builds/macOS

      - name: Publish to GitHub Packages
        uses: softprops/action-gh-release@v1
        with:
          files: macos-unity-build.zip
          tag_name: v${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macOS-Build
          path: Builds/macOS
