name: Build and Publish macOS Unity Project

on: workflow_dispatch

jobs:
  build-plugin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Compile C++ code
        working-directory: Assets/Plugins/TrafficSimulation
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-dev
          pip3 install pybind11
          export PYBIND11_CMAKE_DIR=$(python3 -c "import pybind11; print(pybind11.get_cmake_dir())")
          mkdir build
          cd build
          cmake .. -Dpybind11_DIR=$PYBIND11_CMAKE_DIR
          make
          cd ..

      - name: Upload Plugin Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TrafficSimulation-Plugin
          path: Assets/Plugins/TrafficSimulation/build


  build-unity:
    needs: build-plugin
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Download Plugin Artifact
        uses: actions/download-artifact@v4
        with:
          name: TrafficSimulation-Plugin
          path: Assets/Plugins/TrafficSimulation/build

      - name: Build Unity Project for macOS
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneOSX
          buildName: libReplicantDriveSim
          buildsPath: Builds
          buildMethod: UnityDriveSimulation.BuildScript.PerformMacOSBuild
          customParameters: -development -debugCode

      - name: Package Builds
        run: |
          zip -r macos-unity-build.zip ./Builds/macOS
          zip -r plugin-build.zip ./Assets/Plugins/TrafficSimulation/build

      - name: Publish to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: |
            macos-unity-build.zip
            plugin-build.zip
          tag_name: v${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Unity Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macOS-Unity-Build
          path: ./Builds/macOS
