name: Trigger Read the Docs Build

on:
  push:
    branches:
      - main  # or the branch you want to trigger the build on

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Read the Docs Build
        env:
          READTHEDOCS_TOKEN: ${{ secrets.READTHEDOCS_TOKEN }}  # Ensure this secret is added to GitHub Secrets
        run: |
          curl -X POST -d '' "https://readthedocs.org/api/v3/projects/ReplicantDriveSim/webhook/github/?token=$READTHEDOCS_TOKEN"
