name: Publish Docker Image

on:
  release:
    types: [published] # Triggers when a new release is published
  repository_dispatch:
    types: [trigger_docker_publish] # Triggers when the dispatch event is called
  workflow_run:
    workflows: ["Publish PyPI Package"] # Ensures the Docker workflow runs after the PyPI workflow is completed
    types:
      - completed # Only triggers when the PyPI workflow has successfully completed
  workflow_dispatch:  # Allows manual triggering for debugging

env:
  REGISTRY: ghcr.io
  DOCKER_NAMESPACE: chrisjcc
  DOCKER_REPOSITORY: replicantdrivesim

jobs:
#  wait-for-unity-build:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Wait for Unity Build Artifact
#        uses: fountainhead/action-wait-for-check@v1.1.0
#        with:
#          token: ${{ secrets.GITHUB_TOKEN }}
#          checkName: Publish PyPI Package
#          ref: ${{ github.event.client_payload.ref || github.ref }}
#          timeoutSeconds: 3600

  build-and-push-docker-image:
    #needs: wait-for-unity-build
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name != 'workflow_run' }}
    permissions:
      contents: read
      packages: write
    outputs:
      VERSION: ${{ steps.get_version.outputs.VERSION }}
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0 # Fetch all history including tags

      - name: Determine version
        id: get_version
        run: |
          if [[ ${{ github.event_name }} == 'release' ]]; then
            VERSION="${GITHUB_REF#refs/tags/}"
          elif [[ ${{ github.event_name }} == 'repository_dispatch' ]]; then
            VERSION="${{ github.event.client_payload.version }}"
          else
            VERSION=$(git describe --tags --always) # Use latest tag or commit hash
          fi
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Print version
        run: echo "Building Docker image for version ${{ steps.get_version.outputs.VERSION }}"

      - name: Lowercase the repo name
        run: |
          echo "REPO_LOWER=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_NAMESPACE }}/${{ env.DOCKER_REPOSITORY }}
          tags: |
            type=raw,value=${{ steps.get_version.outputs.VERSION }}
            type=raw,value=latest,enable={{is_default_branch}} 

      - name: Download Unity Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: macOS-unity-Build-project-${{ steps.get_version.outputs.VERSION }}
          path: ./
          #github-token: ${{ secrets.GITHUB_TOKEN }}
          #repository: ${{ github.repository }}
          #run-id: ${{ github.event.workflow_run.id }}

      - name: Extract Unity Build Artifact
        run: |
          unzip macos-unity-build-project-${{ steps.get_version.outputs.VERSION }}.zip
          rm macos-unity-build-project-${{ steps.get_version.outputs.VERSION }}.zip

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
