name: Publish Docker Image

on:
  release:
    types: [published] # Triggers when a new release is published
  repository_dispatch:
    types: [trigger_docker_publish] # Triggers when the dispatch event is called
  workflow_run:
    workflows: ["Publish PyPI Package"] # Ensures the Docker workflow runs after the PyPI workflow is completed
    types:
      - completed # Only triggers when the PyPI workflow has successfully completed
  workflow_dispatch:  # Allows manual triggering for debugging
    inputs:
      run_id:
        description: 'Workflow run ID for artifact download (for manual dispatch)'
        required: false
        default: ''

env:
  REGISTRY: ghcr.io
  DOCKER_NAMESPACE: chrisjcc
  DOCKER_REPOSITORY: replicantdrivesim


jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name != 'workflow_run' }}
    permissions:
      actions: read
      contents: read
      packages: write
    outputs:
      VERSION: ${{ steps.get_version.outputs.VERSION }}
    steps:
      - name: Debug Info
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "SHA: ${{ github.sha }}"
          echo "Ref: ${{ github.ref }}"
          echo "Client Ref : ${{ github.event.client_payload.ref }}"
          echo "Workflow run ID: ${{ github.event.workflow_run.id }}"
          echo "PyPI Run ID: ${{ steps.get-pypi-run.outputs.RUN_ID }}"
          echo "Version: ${{ steps.get_version.outputs.VERSION }}"

      - name: Get latest successful PyPI workflow run
        id: get-pypi-run
        run: |
          WORKFLOW_ID=$(gh api repos/${{ github.repository }}/actions/workflows -q '.workflows[] | select(.name=="Publish PyPI Package") | .id')
          RUN_ID=$(gh api repos/${{ github.repository }}/actions/workflows/$WORKFLOW_ID/runs -q '.workflow_runs[] | select(.conclusion=="success") | .id' | head -n1)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Wait for PyPI Package Publication
        uses: fountainhead/action-wait-for-check@v1.2.0
        id: wait-for-build
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: build-and-publish-pypi
          ref: 673a2c59 #${{ steps.get-pypi-run.outputs.RUN_ID }}
          timeoutSeconds: 3600
          intervalSeconds: 60

      - name: Check build status
        if: steps.wait-for-build.outputs.conclusion != 'success'
        run: |
          echo "Build failed or timed out"
          exit 1

      - name: Checkout Git repository
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0 # Fetch all history including tags

      - name: Determine version and run ID
        id: get_info
        run: |
          if [[ ${{ github.event_name }} == 'release' ]]; then
            VERSION="${GITHUB_REF#refs/tags/}"
          elif [[ ${{ github.event_name }} == 'repository_dispatch' ]]; then
            VERSION="${{ github.event.client_payload.version }}"
          elif [[ ${{ github.event_name }} == 'workflow_run' ]]; then
            VERSION=$(git describe --tags --abbrev=0)
          else
            VERSION=$(git describe --tags --abbrev=0)
          fi
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          
          if [[ ${{ github.event_name }} == 'workflow_run' ]]; then
            echo "RUN_ID=${{ github.event.workflow_run.id }}" >> $GITHUB_OUTPUT
          elif [[ ${{ github.event_name }} == 'workflow_dispatch' ]]; then
            echo "RUN_ID=${{ github.event.inputs.run_id }}" >> $GITHUB_OUTPUT
          else
            echo "RUN_ID=" >> $GITHUB_OUTPUT
          fi

      - name: Print version and run ID
        run: |
          echo "Building Docker image for version ${{ steps.get_info.outputs.VERSION }}"
          echo "Using run ID: ${{ steps.get_info.outputs.RUN_ID }}"

      - name: Lowercase the repo name
        run: |
          echo "REPO_LOWER=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_NAMESPACE }}/${{ env.DOCKER_REPOSITORY }}
          tags: |
            type=raw,value=${{ steps.get_version.outputs.VERSION }}
            type=raw,value=latest,enable={{is_default_branch}} 

      - name: Download Unity Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: macOS-unity-Build-project-v0.2.7 #${{ steps.get_version.outputs.VERSION }}
          path: ./
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          #run-id: ${{ steps.get_info.outputs.RUN_ID }}
          run-id: ${{ steps.get-pypi-run.outputs.RUN_ID }}

      - name: Extract Unity Build Artifact
        run: |
          # Extract the file and overwrite existing files without prompting
          unzip -o macOS-unity-Build-project-v0.2.7.zip #${{ steps.get_version.outputs.VERSION }}.zip

          # Remove the ZIP file
          rm -rf ./macOS-unity-Build-project-v0.2.7.zip #${{ steps.get_version.outputs.VERSION }}.zip

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
